name: starwars_app
description: An example graphql_flutter application utilizing graphql_starwars_test_server

publish_to: none

environment:
  sdk: ">=2.13.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  graphql_flutter:
    path: ../../packages/graphql_flutter
  graphql: ^5.1.2-beta.1
  universal_platform: ^1.0.0+1
    # https://github.com/flutter/flutter/issues/36126#issuecomment-596215587

flutter:
  uses-material-design: true
